### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by PinzhengWang322** [Linear95/SPAG#8]
Thanks for your great work!

Could you please release the trained checkpoints for these SPAG models?

**Comment by Linear95** [comment]
Thank you for your attention to our work. Currently, I am not allowed to release the checkpoints from the company clusters. However, some people from the academy have already reimplemented the SPAG. For example, you can ask [thwu1](https://github.com/thwu1) for accessible checkpoints, by directly commenting at #5.

**Comment by PinzhengWang322** [comment]
Thank you for your guidance!
